angular
  .module('theme.demos', ['flow',
    'oc.lazyLoad',
    'oitozero.ngSweetAlert',
    'LocalStorageModule',
    'ui.bootstrap',
    // 'btford.socket-io',
    // 'webcam',
    'toaster',
    'ngAnimate',
    'theme.components',
    'theme.login',
    'theme.inicio',
    'theme.sede',
    'theme.usuario',
    'theme.pariente',
    'theme.parentesco',
    'theme.historialCitas',
    'theme.programarCita',
    'theme.especialidad' ,
    'theme.resultadolaboratorio',
    'theme.especialidad',
    'theme.analisis',
    'theme.especialidad',
    'theme.venta',
    'theme.procedimientos',
    'theme.procedimientosVirtuales',
    'theme.promociones',
    'theme.promocionesdetalle',
    'theme.resumenpagopromociones',
    'theme.resumenpagopromociones',
    'theme.compraResumenController',
    'theme.redirectToPromociones',
    'theme.subscribete',
    'theme.bannerPromocion',
    'theme.atencionesPendientes'
  ]);